apiVersion: v1
kind: ConfigMap
metadata:
  name: mopidy-config
  labels:
    app: mopidy
data:
  mopidy.conf: |
    # For information about configuration values that can be set in this file see:
    #
    #   https://docs.mopidy.com/en/latest/config/
    #
    # Run `sudo mopidyctl config` to see the current effective config, based on
    # both defaults and this configuration file.
    
    # Lovely docs here: https://github.com/jaedb/Iris/wiki/Getting-started
    [http]
    hostname = 0.0.0.0
    default_app = iris
    
    [spotify]
    username =  
    password = 
    # Get these here: https://mopidy.com/ext/spotify/
    client_id = 
    client_secret = 
    bitrate = 320
    toplist_countries = GB
    
    [iris]
    country = GB
    locale = en_GB
    
    [audio]
    # Please change the password from hackme here and in the icecast configmap!
    output = lamemp3enc bitrate=320 ! shout2send async=false mount=listen ip=icecast port=8000 password=hackme
 
